"""
report.py
---------
Builds a downloadable investigation report from the analysis results,
in two formats:
- Markdown (always works, zero dependency risk)
- PDF (via fpdf2 -- lightweight, no system dependencies, safe for cloud deploy)
"""

from datetime import datetime


# ---------------------------------------------------------------------------
# Markdown report
# ---------------------------------------------------------------------------

def generate_markdown_report(question: str, timeline_events: list,
                             root_cause: dict, alternative_causes: list,
                             reasoning_summary: str = "") -> str:
    lines = []
    lines.append("# Root Cause Investigation Report")
    lines.append(f"*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}*")
    lines.append("")
    lines.append(f"**Question asked:** {question}")
    lines.append("")

    lines.append("## Likely Root Cause")
    if root_cause:
        lines.append(f"**{root_cause.get('description', 'N/A')}**")
        lines.append(f"Confidence: **{root_cause.get('confidence', 0)}%**")
        lines.append("")
        evidence = root_cause.get("supporting_evidence", [])
        if evidence:
            lines.append("Supporting evidence:")
            for item in evidence:
                lines.append(f"- {item}")
        sources = root_cause.get("evidence_sources", [])
        if sources:
            lines.append("")
            lines.append(f"Evidence sources: {', '.join(sources)}")
    else:
        lines.append("_No root cause identified yet._")
    lines.append("")

    lines.append("## Alternative Explanations")
    if alternative_causes:
        for alt in alternative_causes:
            desc = alt.get("description", "N/A")
            conf = alt.get("confidence", 0)
            lines.append(f"- **{desc}** — Confidence: {conf}%")
    else:
        lines.append("_None identified._")
    lines.append("")

    lines.append("## Evidence Timeline")
    if timeline_events:
        lines.append("| Date | Type | Description | Source |")
        lines.append("|------|------|-------------|--------|")
        for e in timeline_events:
            date = e.get("date", "")
            etype = e.get("classification", e.get("type", ""))
            desc = str(e.get("description", "")).replace("|", "/")
            source = e.get("source_file", "")
            lines.append(f"| {date} | {etype} | {desc} | {source} |")
    else:
        lines.append("_No evidence timeline available._")
    lines.append("")

    if reasoning_summary:
        lines.append("## Reasoning Summary")
        lines.append(reasoning_summary)
        lines.append("")

    lines.append("---")
    lines.append("*Generated by Root Cause AI Investigator*")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# PDF report
# ---------------------------------------------------------------------------

def _safe_text(text) -> str:
    """
    fpdf2's built-in core fonts only support latin-1. Rather than crash on
    emoji/unicode from LLM output, we degrade gracefully.
    """
    if text is None:
        return ""
    text = str(text)
    return text.encode("latin-1", errors="replace").decode("latin-1")


def generate_pdf_report(question: str, timeline_events: list,
                         root_cause: dict, alternative_causes: list,
                         reasoning_summary: str = "") -> bytes:
    from fpdf import FPDF

    pdf = FPDF()
    pdf.set_margins(10, 10, 10)
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 12, _safe_text("Root Cause Investigation Report"), ln=True)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 6, _safe_text(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}"), ln=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    # Question
    pdf.set_font("Helvetica", "B", 12)
    pdf.multi_cell(0, 7, _safe_text(f"Question asked: {question}"), wrapmode="CHAR")
    pdf.ln(2)

    # Root cause section
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, _safe_text("Likely Root Cause"), ln=True)

    if root_cause:
        pdf.set_font("Helvetica", "B", 12)
        pdf.multi_cell(0, 7, _safe_text(root_cause.get("description", "N/A")), wrapmode="CHAR")

        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(200, 30, 30)
        pdf.cell(0, 8, _safe_text(f"Confidence: {root_cause.get('confidence', 0)}%"), ln=True)
        pdf.set_text_color(0, 0, 0)

        evidence = root_cause.get("supporting_evidence", [])
        if evidence:
            pdf.set_font("Helvetica", "", 11)
            pdf.cell(0, 7, _safe_text("Supporting evidence:"), ln=True)
            for item in evidence:
                pdf.multi_cell(0, 6, _safe_text(f"  - {item}"), wrapmode="CHAR")

        sources = root_cause.get("evidence_sources", [])
        if sources:
            pdf.set_font("Helvetica", "I", 10)
            pdf.multi_cell(0, 6, _safe_text(f"Evidence sources: {', '.join(sources)}"), wrapmode="CHAR")
    else:
        pdf.set_font("Helvetica", "I", 11)
        pdf.cell(0, 7, _safe_text("No root cause identified yet."), ln=True)
    pdf.ln(4)

    # Alternative explanations
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, _safe_text("Alternative Explanations"), ln=True)
    pdf.set_font("Helvetica", "", 11)
    if alternative_causes:
        for alt in alternative_causes:
            desc = alt.get("description", "N/A")
            conf = alt.get("confidence", 0)
            pdf.multi_cell(0, 6, _safe_text(f"- {desc} (Confidence: {conf}%)"), wrapmode="CHAR")
    else:
        pdf.cell(0, 7, _safe_text("None identified."), ln=True)
    pdf.ln(4)

    # Evidence timeline
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, _safe_text("Evidence Timeline"), ln=True)
    pdf.set_font("Helvetica", "", 9)

    if timeline_events:
        col_widths = [24, 28, 108, 28]
        headers = ["Date", "Type", "Description", "Source"]
        pdf.set_font("Helvetica", "B", 9)
        for w, h in zip(col_widths, headers):
            pdf.cell(w, 7, _safe_text(h), border=1)
        pdf.ln()

        pdf.set_font("Helvetica", "", 8)
        for e in timeline_events:
            date = _safe_text(e.get("date", ""))
            etype = _safe_text(e.get("classification", e.get("type", "")))
            desc = _safe_text(e.get("description", ""))[:65]
            source = _safe_text(e.get("source_file", ""))[:16]

            pdf.cell(col_widths[0], 6, date, border=1)
            pdf.cell(col_widths[1], 6, etype, border=1)
            pdf.cell(col_widths[2], 6, desc, border=1)
            pdf.cell(col_widths[3], 6, source, border=1)
            pdf.ln()
    else:
        pdf.cell(0, 7, _safe_text("No evidence timeline available."), ln=True)
    pdf.ln(4)

    # Reasoning summary
    if reasoning_summary:
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, _safe_text("Reasoning Summary"), ln=True)
        pdf.set_font("Helvetica", "", 11)
        pdf.multi_cell(0, 6, _safe_text(reasoning_summary), wrapmode="CHAR")

    # fpdf2 returns a bytearray with dest="S"; normalize to bytes for Streamlit's download_button
    return bytes(pdf.output(dest="S"))